name: "Print All Events"
on:
  workflow_dispatch:
  pull_request_target:
  paths:
      - packages/ui/**
jobs: 
    echo:
      name: Print All
      runs-on: ubuntu-latest
      steps:
        - name: echo env
          run: |
            ls
            pwd
